#!/usr/bin/env node
// Builds assets/icons/sprite.svg from Lucide (ISC) SVG sources.
// Usage: node tools/build-icons.mjs [path/to/lucide-static/icons]
// Symbol ids are the Lucide names. Each symbol: viewBox 0 0 24 24, fill none, stroke currentColor, stroke-width 1.5.
import { readFileSync, writeFileSync, existsSync, copyFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = process.argv[2] || '/tmp/claude-0/-home-user-forge/7545d543-999d-5fb6-b514-71e2c86cd347/scratchpad/npmw/node_modules/lucide-static/icons';

export const ICONS = [
  // arrows / chevrons
  'arrow-right', 'arrow-left', 'arrow-up', 'arrow-down', 'arrow-up-right', 'arrow-down-right', 'arrow-up-left',
  'chevron-right', 'chevron-left', 'chevron-up', 'chevron-down', 'chevrons-right', 'chevrons-left', 'move-right',
  'corner-down-left', 'arrow-up-down',
  // UI
  'menu', 'x', 'search', 'globe', 'languages', 'plus', 'minus', 'check', 'copy', 'external-link', 'filter',
  'sliders-horizontal', 'layout-grid', 'list', 'map', 'map-pin', 'zoom-in', 'zoom-out', 'maximize', 'minimize',
  'maximize-2', 'download', 'upload', 'play', 'pause', 'rotate-3d', 'rotate-ccw', 'refresh-cw', 'box', 'boxes', 'layers',
  'scan', 'eye', 'eye-off', 'camera', 'image', 'images', 'sun', 'moon', 'sunrise', 'sunset', 'info', 'circle-help',
  'mouse-pointer-click', 'mouse', 'move', 'hand', 'keyboard', 'share-2', 'send', 'mail', 'phone', 'clock', 'calendar',
  'file-text', 'file-up', 'paperclip', 'sparkles', 'loader-circle', 'triangle-alert', 'circle-check', 'circle-x',
  'circle-alert', 'link', 'cookie', 'grip-vertical', 'ellipsis', 'trash-2', 'video', 'newspaper', 'printer',
  // domain
  'building', 'building-2', 'hotel', 'hospital', 'school', 'graduation-cap', 'landmark', 'store', 'shopping-bag',
  'house', 'warehouse', 'factory', 'trees', 'tree-palm', 'waves', 'construction', 'hard-hat', 'ruler',
  'drafting-compass', 'pencil-ruler', 'hammer', 'wrench', 'shovel', 'shield-check', 'award', 'target', 'lightbulb',
  'leaf', 'handshake', 'users', 'user-round', 'briefcase', 'globe-2', 'earth', 'compass', 'route', 'gauge',
  'chart-line', 'chart-bar', 'trending-up', 'badge-check', 'scale', 'network', 'workflow', 'git-merge', 'puzzle',
  'heart-pulse', 'book-open', 'medal', 'blocks', 'clipboard-check', 'cog', 'milestone', 'flag', 'plane',
  // added in the integration pass (page requests)
  'pencil', 'navigation', 'map-pinned', 'box-select', 'sun-moon', 'scissors', 'concierge-bell', 'key-round', 'key',
  'door-open', 'quote',
];

const out = [];
const missing = [];
for (const name of [...new Set(ICONS)]) {
  const file = join(SRC, `${name}.svg`);
  if (!existsSync(file)) { missing.push(name); continue; }
  const raw = readFileSync(file, 'utf8');
  const inner = raw
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\s*\n\s*/g, '')
    .trim();
  out.push(`<symbol id="${name}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${inner}</symbol>`);
}

const sprite = `<svg xmlns="http://www.w3.org/2000/svg">
<!-- Icons: Lucide (https://lucide.dev) — ISC License, see assets/icons/LICENSE. Generated by tools/build-icons.mjs -->
${out.join('\n')}
</svg>
`;
mkdirSync(join(ROOT, 'assets/icons'), { recursive: true });
writeFileSync(join(ROOT, 'assets/icons/sprite.svg'), sprite);
const lic = join(SRC, '..', 'LICENSE');
if (existsSync(lic)) copyFileSync(lic, join(ROOT, 'assets/icons/LICENSE'));
console.log(`sprite.svg: ${out.length} symbols${missing.length ? `; skipped missing: ${missing.join(', ')}` : ''}`);
